### ISSUE TITLE
Error opening project

### ISSUE THREAD

**Issue by michielhemme** [JamJar00/DarkRift-MySQLConnector#2]
When I'm trying to open the project it first promps me the message:

"Team Foundation Server Version Control
The solution you are opening is bound to source control.."

When I press yes i get the message

"The solution appreas to be under source control, but it's binding informatio cannot be found. Because it is not possible to recover this missing information automatically, the projects whose bindings are missing will be treated as not under source control."

This resulting in not finding Darkrift, Darkrift.ConfigTools, DarkRift.Storage making me unable to compile

**Comment by JamJar00** [comment]
Hmm what happens if you press no? 😄

**Comment by AsoraX** [comment]
That what he wrote... If u klick on "No" you got no chance to compile because of the missing Darkrift part ;)

**Comment by JamJar00** [comment]
You need to update references in this project to point to your versions of the DLL files anyway, they don't come with this plugin. Granted, it shouldn't really be bound to my source control still though, looks like Visual Studio has left in a reference it shouldn't have.

So pressing "no" and then updating your references seems to be the solution to me?

**Comment by AsoraX** [comment]
We just have to Copy & Paste the Darkrift.dll from the Server\Lib folder into VS ;)

**Comment by JamJar00** [comment]
https://forum.unity3d.com/threads/darkrift-networking-2-the-next-level-of-networking.380800/ :)
