### ISSUE TITLE
I can't compile connector.cs

### ISSUE THREAD

**Issue by fedecaccia** [JamJar00/DarkRift-MySQLConnector#3]
Even when I update the darkreif.dll reference, commpiling throw multiple errors:
-  C# The type or namespace name 'ConfigTools' does not exist in the namespace (are you missing an assembly reference?)
-  C# The type or namespace name 'Storage' does not exist in the namespace (are you missing an assembly reference?)
- ...

**Comment by JamJar00** [comment]
As discussed on the [forum](https://forum.unity.com/threads/darkrift-networking-2-the-next-level-of-networking.380800/page-7#post-3949732), this repository is for the original DarkRift and isn't supported with DarkRift 2!

Feel free to reopen this issue if you think that's not the problem!
